# Generated by Django 4.1.2 on 2022-10-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall_rules',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
        migrations.AddField(
            model_name='interface',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
        migrations.AddField(
            model_name='nat_rules',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
        migrations.AddField(
            model_name='route_table',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
