# Generated by Django 4.1.2 on 2022-11-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rules', '0002_firewall_rules_pub_date_interface_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='firewall_practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
