# Generated by Django 4.1.2 on 2022-11-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_rules', '0004_firewall_rules_firewall_practice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
